# For more info on HTTP files go to https://aka.ms/vs/httpfile
# Postman | Insomnia

### Get list of clients
GET http://localhost:5173/api/clients

### Register a new client
POST http://localhost:5173/api/clients
Content-Type: application/json

{
    "Name": "Philipe"
}

### Update a client
PUT http://localhost:5173/api/clients/3
Content-Type: application/json

{
    "Name": "Mary Antonieta"
}

### Delete a client
DELETE http://localhost:5173/api/clients/2